using Microsoft.CodeAnalysis;
using System.Text;

namespace ZeroAlloc.Mapping.Generator;

internal static class MapEmitter
{
    public static string Emit(MapperClass cls, Compilation comp)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n#nullable enable\n");

        if (!string.IsNullOrEmpty(cls.Namespace))
        {
            sb.Append("namespace ").Append(cls.Namespace).Append(";\n\n");
        }

        sb.Append("partial class ").Append(cls.ClassName).Append("\n{\n");

        foreach (var decl in cls.Mappings)
        {
            var src = comp.GetTypeByMetadataName(StripGlobal(decl.SourceTypeFqn))
                      ?? FindType(comp, decl.SourceTypeFqn);
            var dst = comp.GetTypeByMetadataName(StripGlobal(decl.DestinationTypeFqn))
                      ?? FindType(comp, decl.DestinationTypeFqn);
            if (src is null || dst is null) continue;

            var match = PropertyMatcher.Match(src, dst);
            if (match is null) continue;

            EmitMapMethod(sb, decl, match);
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static void EmitMapMethod(StringBuilder sb, MappingDecl decl, MatchResult match)
    {
        sb.Append("    public static ").Append(decl.DestinationTypeFqn).Append(" Map(")
          .Append(decl.SourceTypeFqn).Append(" src)\n    {\n");
        sb.Append("        global::System.ArgumentNullException.ThrowIfNull(src);\n");
        sb.Append("        return new ").Append(decl.DestinationTypeFqn).Append("(\n");

        for (int i = 0; i < match.Mappings.Count; i++)
        {
            var m = match.Mappings[i];
            sb.Append("            ").Append(m.TargetParamName).Append(": src.").Append(m.SourcePropertyName);
            if (i < match.Mappings.Count - 1) sb.Append(',');
            sb.Append('\n');
        }

        sb.Append("        );\n    }\n");
    }

    private static string StripGlobal(string fqn) =>
        fqn.StartsWith("global::", System.StringComparison.Ordinal) ? fqn.Substring(8) : fqn;

    private static INamedTypeSymbol? FindType(Compilation comp, string fqn)
    {
        var stripped = StripGlobal(fqn);
        foreach (var assembly in comp.References
                     .Select(r => comp.GetAssemblyOrModuleSymbol(r))
                     .OfType<IAssemblySymbol>()
                     .Concat(new[] { comp.Assembly }))
        {
            var t = assembly.GetTypeByMetadataName(stripped);
            if (t is not null) return t;
        }
        return null;
    }
}
