using Microsoft.CodeAnalysis;
using System.Text;

namespace ZeroAlloc.Mapping.Generator;

internal static class MapEmitter
{
    public static string Emit(MapperClass cls, Compilation comp)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n#nullable enable\n");

        if (!string.IsNullOrEmpty(cls.Namespace))
        {
            sb.Append("namespace ").Append(cls.Namespace).Append(";\n\n");
        }

        sb.Append("partial class ").Append(cls.ClassName).Append("\n{\n");

        foreach (var decl in cls.Mappings)
        {
            var src = comp.GetTypeByMetadataName(StripGlobal(decl.SourceTypeFqn))
                      ?? FindType(comp, decl.SourceTypeFqn);
            var dst = comp.GetTypeByMetadataName(StripGlobal(decl.DestinationTypeFqn))
                      ?? FindType(comp, decl.DestinationTypeFqn);
            if (src is null || dst is null) continue;

            var match = PropertyMatcher.Match(src, dst, decl.UserPartialMethod);
            if (match is null) continue;

            if (decl.Kind == MappingKind.TryMap)
                TryMapEmitter.EmitTryMapMethod(sb, decl, match, cls, comp);
            else
                EmitMapMethod(sb, decl, match, cls, comp);
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static void EmitMapMethod(StringBuilder sb, MappingDecl decl, MatchResult match, MapperClass owningClass, Compilation comp)
    {
        var partialKw = decl.UserPartialMethod is not null ? "partial " : "";
        sb.Append("    public static ").Append(partialKw).Append(decl.DestinationTypeFqn).Append(" Map(")
          .Append(decl.SourceTypeFqn).Append(" src)\n    {\n");
        sb.Append("        global::System.ArgumentNullException.ThrowIfNull(src);\n");
        sb.Append("        return new ").Append(decl.DestinationTypeFqn).Append("(\n");

        var totalArgs = match.Mappings.Count + match.Constants.Count;
        var idx = 0;

        foreach (var m in match.Mappings)
        {
            var expr = ResolveExpression(m, owningClass, comp);
            sb.Append("            ").Append(m.TargetParamName).Append(": ").Append(expr);
            if (++idx < totalArgs) sb.Append(',');
            sb.Append('\n');
        }

        foreach (var c in match.Constants)
        {
            sb.Append("            ").Append(c.TargetParamName).Append(": ").Append(FormatLiteral(c.Value));
            if (++idx < totalArgs) sb.Append(',');
            sb.Append('\n');
        }

        sb.Append("        );\n    }\n");
    }

    private static string ResolveExpression(PropertyMapping m, MapperClass owningClass, Compilation comp)
    {
        var srcExpr = "src." + m.SourcePropertyName;

        // Collection?
        var srcColl = NestedMappingResolver.AsCollection(m.SourceType);
        var dstColl = NestedMappingResolver.AsCollection(m.TargetType);
        if (srcColl is not null && dstColl is not null)
        {
            var nested = NestedMappingResolver.FindNestedMapper(owningClass, srcColl.Value.Element, dstColl.Value.Element);
            if (nested is not null)
            {
                var dstFqn = m.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return MakeCollectionExpression(srcExpr, srcColl.Value.Element, dstColl.Value.Element, dstFqn, dstColl.Value.CollectionKind);
            }
        }

        // Nested object via declared mapper?
        var nestedObj = NestedMappingResolver.FindNestedMapper(owningClass, m.SourceType, m.TargetType);
        if (nestedObj is not null)
        {
            return "Map(" + srcExpr + ")";
        }

        // Standard conversion
        var conv = ConversionResolver.Resolve(m.SourceType, m.TargetType, comp);
        return ConversionResolver.Apply(conv, srcExpr, m.TargetType);
    }

    private static string MakeCollectionExpression(string srcExpr, ITypeSymbol srcElem, ITypeSymbol dstElem, string dstFqn, string kind)
    {
        var dstElemFqn = dstElem.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var listOfDst = "global::System.Collections.Generic.List<" + dstElemFqn + ">";
        var loop = "(global::System.Linq.Enumerable.Select(" + srcExpr + ", static x => Map(x)))";
        if (kind == "array")
            return "global::System.Linq.Enumerable.ToArray" + loop;
        return "global::System.Linq.Enumerable.ToList" + loop;
    }

    private static string FormatLiteral(object? value) => value switch
    {
        null => "null",
        string s => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
        bool b => b ? "true" : "false",
        char c => "'" + c + "'",
        _ => value.ToString() ?? "null",
    };

    private static string StripGlobal(string fqn) =>
        fqn.StartsWith("global::", System.StringComparison.Ordinal) ? fqn.Substring(8) : fqn;

    private static INamedTypeSymbol? FindType(Compilation comp, string fqn)
    {
        var stripped = StripGlobal(fqn);
        foreach (var assembly in comp.References
                     .Select(r => comp.GetAssemblyOrModuleSymbol(r))
                     .OfType<IAssemblySymbol>()
                     .Concat(new[] { comp.Assembly }))
        {
            var t = assembly.GetTypeByMetadataName(stripped);
            if (t is not null) return t;
        }
        return null;
    }
}
